[WIP] feat: add photosController
rento2/rento2 pull request #10
Opened 2022-02-03 13:09 UTC by RimidalU

2022-02-18 20:40 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    if (photos != null && photos !== undefined) {
Если делаешь != null, то это автоматически проверяет на !== undefined. Ты наверно имел в виду !== null, но это как раз единственный кейс, когда нестрогая проверка оправдана.

2022-02-18 20:42 UTC, AntePost commented on packages/backend/database/factories/Photo.ts
> +export interface IPhotoFactory {
А сюда нельзя прямо модель передать в качестве параметра? Чтобы не дублировать интерфейс.

2022-02-18 20:42 UTC, AntePost commented on packages/backend/database/seeders/Photo.ts
> +    // Write your database queries inside the run method
```suggestion
```

2022-02-19 21:03 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    if (photos != null && photos !== undefined) {
Косякнул, но узнал новое)))

2022-03-12 12:23 UTC, AntePost requested changes
Вопрос: фото будут доступны по ссылке, которая возвращается get запросом?

Заданные вопросы:
"1. Я Залез в контроллер @lgmarch, что бы мой подтягивал оттуда ID.
2 Может быть не нужно поле 'link' ? если реализовать так, как я сделал (имя формируется из id картинки)
3 Насколько нам нужны другие форматы кроме jpg - просто я не нагуглил как сделать в поиске (в дестрой котроллера фото) произвольное расширение (типо "*" в некоторых программах).
4 нужно ли реализовывать что бы методы гет и гет олл отдавали сформированные пути к картинке или для этого достаточно отдавать id файла (как сейчас) и фронт сам сформирует из него полный путь?
5 метод замены так норм или нужно сделать через удаление прошлой картинки и созданию новой?"

По заданным вопросам:
1) Ок. @lgmarch, есть небольшое изменение в apartmentController, учитывай.
2) Пока не нужно, но как-то стремно отдавать ссылки вида /photos/1.jpg. Можно либо использовать UUID, чтобы выглядело лучше, либо дать возможность выбирать название.
3) Отписался в коде
4) Зависит от вопросов 2 и 3, думаю лучше отдавать.
5) Возможно вообще не нужен update, не вижу пока для него use case. Тоже зависит от вопроса 2.

2022-03-12 12:23 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      meta: { upload: fileName },
upload - неясно, что тут должно лежать. Лучше просто filename.

2022-03-12 12:23 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    const photos = await Photo.findBy('id', params['id'])
Почему множественное число?

2022-03-12 12:23 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +        overwrite: true
Это здесь нужно?

2022-03-12 12:23 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      await Drive.delete(`${photos.id}.jpg`)
Чтобы знать расширение файла, можно записывать информацию о расширении в таблицу БД.

2022-03-12 12:23 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      data: { photos }
А что в данном случае возвращается?

2022-03-12 12:23 UTC, AntePost commented on packages/backend/database/factories/Photo.ts
> +    // apartment_id: faker.datatype.number(),
Почему закомментировано?

2022-03-12 12:23 UTC, AntePost commented on packages/backend/start/routes.ts
> +  </form>`
Это здесь зачем?

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/start/routes.ts
> +  </form>`
смотрел возможности фронта в Адонисе. И мне так проще было отправлять картинку и тело запроса при тестировании. удалил.

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/database/factories/Photo.ts
> +    // apartment_id: faker.datatype.number(),
забыл удалить. исправил

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      data: { photos }
само тело запроса. Изменил, т.к. оно не нужно.

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      await Drive.delete(`${photos.id}.jpg`)
добавил UUID и сделал полный путь в ячейке "link" таблицы (как и было в старой ренте)

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    const photos = await Photo.findBy('id', params['id'])
ошибка. поменял

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +      meta: { upload: fileName },
изменил

2022-03-31 20:39 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    const uploadPicture = await request.validate({ schema: photoSchema })
поменял

2022-04-01 14:09 UTC, AntePost requested changes
В целом неплохо. Надо точно сделать привязку к квартире, то есть в POST указывать apartmentId.

Это я тебе посоветовал все оборачивать в try/catch?

Еще можешь глянуть как сделана сущность reviews, например в том, как мы там ответы на запросы делаем.

2022-04-01 14:09 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    } catch (e: any) {
Лучше использовать unknown: https://stackoverflow.com/questions/64452484/how-can-i-safely-access-caught-error-properties-in-typescript/64452744#64452744

2022-04-01 16:06 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +const { v4: uuidv4 } = require('uuid')
Эта библиотека по другому (через импор-фром или импорт=реквае) не притягивается. Я рассматривал этот вариант, но тогда нужно до устанавливать новые файлы. Я посчитал, что если уже есть, то зачем тащить что-то новое... Если нужно - переделаю.

2022-04-01 16:07 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +    } catch (e: any) {
Спасибо! Не знал про него - переделаю

2022-04-06 09:08 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +const { v4: uuidv4 } = require('uuid')
По поводу try/catch не помню - давно уже использую, может быть и ты. Понравилось, что пишешь код в одном блоке, а ошибки обрабатываются в отдельном - всё прозрачно.

2022-04-06 09:30 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +const { v4: uuidv4 } = require('uuid')
Это не стоит делать. У нас стоит глобальный обработчик ошибок во фреймворке, он схватит если что. Обрабатывать нужно там, где мы не уверены, в том что отработает корректно или хотим как-то по особому обработать ошибку. Например, при запросе данные со стороннего API, или когда валидируешь что-то. Если в catch просто логирование, то обычно он не нужен (если специально что-то не дебажим в этом месте).

2022-04-06 09:44 UTC, AntePost requested changes
У тебя конфликты, обрати внимание.

2022-04-06 09:44 UTC, AntePost commented on packages/backend/.gitignore
> +_docker
Перенеси записи из корневого gitignore.

2022-04-06 09:44 UTC, AntePost commented on packages/backend/.gitignore
> +Dockerfile
Это как раз-таки не в gitingore.

2022-04-06 09:44 UTC, AntePost commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +const { v4: uuidv4 } = require('uuid')
Можешь посмотреть в reviews как сделано.

2022-04-06 09:44 UTC, AntePost commented on packages/backend/app/Validators/PhotoValidator.ts
> +  public schema = schema.create({
Может сюда photoSchema перенести?

2022-04-06 09:44 UTC, AntePost commented on packages/backend/docker-compose.yaml
> +    image: mysql:8.0
Не понял? Ты mysql вернул?

2022-04-06 12:04 UTC, RimidalU commented on packages/backend/app/Controllers/Http/PhotosController.ts
> +const { v4: uuidv4 } = require('uuid')
Опять-таки не знал про это((( Я когда делал - смотрел - еще даже удивился, что не сделана обработка ошибок ))) Уберу.

2022-04-06 12:05 UTC, RimidalU commented on packages/backend/app/Validators/PhotoValidator.ts
> +  public schema = schema.create({
хорошо!

2022-04-06 14:27 UTC, RimidalU commented on packages/backend/docker-compose.yaml
> +    image: mysql:8.0
упс.... ((((

2022-04-07 15:06 UTC, AntePost requested changes

2022-04-07 15:06 UTC, AntePost commented on packages/backend/app/Validators/PhotoValidator.ts
> +export class PhotoValidator {
А этот валидатор ты где-то используешь?

2022-04-07 15:06 UTC, AntePost commented on packages/backend/.gitignore
> +_docker/data/.gitkeep
Неправильно перенес из корневого gitignore. И там можно удалить.

2022-04-07 17:15 UTC, AntePost requested changes

2022-04-07 17:15 UTC, AntePost commented on packages/backend/.gitignore
> +!_docker/data/.gitkeep
Верни еще сам файл обратно.

2022-04-07 18:38 UTC, RimidalU commented on packages/backend/.gitignore
> +!_docker/data/.gitkeep
ссори(( только сегодня узнал что это за файл и зачем '!' в начале пути к нему

2022-04-07 18:41 UTC, AntePost approved these changes

2022-04-07 18:41 UTC, merged