apartment component added
rento2/rento2 pull request #102
Opened 2022-07-07 08:57 UTC by AndMuruGvart

2022-07-07 09:19 UTC, AntePost requested changes
Этот PR тебе больше не нужен?
https://github.com/rento2/rento2/pull/81

2022-07-07 09:19 UTC, AntePost commented on packages/admin/src/components/Apartment/ApartmentCreate.tsx
>        <FormTab label="Step 1">
Лучше дать понятный label.

2022-07-07 09:19 UTC, AntePost commented on packages/admin/src/components/Apartment/ApartmentEdit.tsx
>  const ApartmentEdit: FC<ListProps> = props => (
Нельзя как-то этот компонент объединить с create, чтобы не копипастить?

2022-07-07 09:19 UTC, AntePost commented on packages/admin/src/components/Apartment/ApartmentList.tsx
> +/* eslint-disable react/jsx-key */
key - это нужный аттрибут в jsx.

https://reactjs.org/docs/lists-and-keys.html#keys

2022-07-07 09:19 UTC, AntePost commented on packages/admin/src/components/Apartment/ApartmentList.tsx
> +  <TextInput defaultValue="Hello, World!"
Лучше осмысленный default поставить.

2022-07-08 07:15 UTC, AndMuruGvart commented on packages/admin/src/components/Apartment/ApartmentCreate.tsx
>        <FormTab label="Step 1">
#81 больше не нужен, можно удалять

2022-07-08 07:16 UTC, AndMuruGvart commented
> 



> Этот PR тебе больше не нужен? #81



> Этот PR тебе больше не нужен? #81
Думкаю, можно удалить

2022-07-08 07:49 UTC, AndMuruGvart commented
> Этот PR тебе больше не нужен? #81

Можно удалить, думаю

2022-07-08 07:53 UTC, AndMuruGvart commented on packages/admin/src/components/Apartment/ApartmentEdit.tsx
>  const ApartmentEdit: FC<ListProps> = props => (
На 100 процентов не уверен, но в документации они их разделяют

2022-10-12 13:25 UTC, closed without merging