Lmarch/migration
rento2/rento2 pull request #12
Opened 2022-02-05 08:31 UTC by lgmarch

2022-02-18 17:49 UTC, AntePost requested changes
В целом я только в одном месте писал замечание, а не во всех. Поэтому править не только в этом месте, но и во всех.

2022-02-18 17:49 UTC, AntePost commented on packages/backend/app/Validators/CreateAccommodationValidator.ts
> +export default class CreateAccommodationValidator extends ValidatorMessages {
В целом странно звучит такой extend. Как Validator может наследоваться от Messages?

Ты говорила, что хочешь что-то тут переделать, может тогда станет понятней.

2022-02-18 18:32 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +    pivotTimestamps: true
Тут указывается, так как это поле заполняется при создании новой записи в Апартаментах Тогда, если "pivotTimestamps: true" указать, поле в таблице отношений заполнится автоматом. Я не заполняю таблицу отношений отдельно от других таблиц. Т.е. там оно не нужно.

2022-02-18 18:33 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +  public geoCoordinateX!: string
Что вообще это за формат?

2022-02-18 18:37 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    return response.status(HttpCode.OK).json(creatingOkMsg(apartments))
ДА, сделаю. Данные для этого подготовлены.

2022-02-18 18:38 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const id: string = request.params()['id']
А разве не Стринг? Но Валидация нужна...

2022-02-18 18:42 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    await request.validate(CreateApartmentValidator)
Да, и опять вопрос по соглашениям: какие данные обязательные? Ведь в Валидаторе я могу кое-что отсеять, кое-что добавить, что-то переименовать! Давайте обсуждать интерфейс обмена данными

2022-02-18 18:47 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +      const accommodation = await Accommodation.create(item)
Вот и я думаю, тут надо что-то типа Транзакций.

2022-02-18 18:48 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const apartmentCreate = await Apartment.query().where('id', apartment.id).preload('accommodations')
Можно и так. Меньше обращений к БД

2022-02-18 18:49 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +  public novoId!: number
:)

2022-02-18 18:51 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +    pivotTimestamps: true
То есть если я заполняю Аккоммодации, то не заполняю таблицу отношений.

2022-02-18 18:53 UTC, lgmarch commented on packages/backend/app/Validators/CreateAccommodationValidator.ts
> +export default class CreateAccommodationValidator extends ValidatorMessages {
Ошибок при валидации данных со Фронта.

2022-02-18 18:55 UTC, lgmarch commented on packages/backend/common/interfaces/accommodation-int.ts
> +export interface AccommodationInt {
Надо договориться договориться как называть. Чтобы везде было одинаково. Говори, я поправлю. :)

2022-02-18 18:57 UTC, lgmarch commented on packages/backend/database/factories/AccommodationsFactory.ts
> +      name: faker.name.firstName(),
Тут, если не firstName не проходит, так как надо уникальное значение. У меня только это работает без сбоев, при других он умудряется не уникальное значение вставлять иногда. Ну это-же не так важно. Данные-то норм.

2022-02-18 18:58 UTC, lgmarch commented on packages/backend/database/factories/ApartmentsFactory.ts
> +      location: 0,
Тут у меня били ошибки, я поправила, но похоже не с той ветки слила. Вообще, формат тут мне не понятен.

2022-02-18 19:03 UTC, lgmarch commented on packages/backend/database/migrations/1643867952130_banners_to_apartments.ts
> +      table.foreign('apartment_id').references('id').inTable('apartments')
Да, надо уменьшить код. И нагляднее

2022-02-18 19:05 UTC, lgmarch commented on packages/backend/database/migrations/1643872223276_photos.ts
> +import BaseSchema from '@ioc:Adonis/Lucid/Schema'
Это-же миграция. Она была изначально. Я все миграции сделала сразу.

2022-02-18 19:06 UTC, lgmarch commented on packages/backend/database/migrations/1643769081230_apartments.ts
> +      table.string('description', 1024).nullable()
А где все-же они нужны? Где нет? Я не знаю. Я в таблице по БД ввела даже столбец по типам данных. Кто знает, что надо, отредактируйте!

2022-02-18 19:09 UTC, lgmarch commented on packages/backend/database/migrations/1643867561896_banners.ts
> +      table.timestamp('created_at').nullable()
Я считаю, что это надо будет сделать, когда человек будет отрабатывать соответствующую Модель. Сейчас смысла нет.

2022-02-18 19:09 UTC, lgmarch commented on packages/backend/start/routes/apartment.ts
> +import Route from '@ioc:Adonis/Core/Route'
Просто я это сделала, так как там будем прописывать Midleware. И еще куча всяких возможностей.

2022-02-18 20:16 UTC, AntePost commented on packages/backend/database/migrations/1643874014246_sleeping_places.ts
> +      table.enum('type', ['bed', 'sofa']).nullable()
Ну дело вкуса, по-моему лучше сразу выносить, если понятно, что это будет нужно в будущем. Чтобы не забыть.

2022-02-18 20:16 UTC, AntePost commented on packages/backend/database/migrations/1643867561896_banners.ts
> +      table.timestamp('created_at').nullable()
Скажем так, эти поля при стандартной работе с ними не могут быть null.

2022-02-18 20:17 UTC, AntePost commented on packages/backend/start/routes/apartment.ts
> +import Route from '@ioc:Adonis/Core/Route'
Дело вкуса. Я бы объединил, но оставляю на твое усмотрение.

2022-02-18 20:18 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const id: string = request.params()['id']
Потому что в БД это int.

2022-02-18 20:20 UTC, AntePost commented on packages/backend/app/Models/Apartment.ts
> +  public geoCoordinateX!: string
59.344310, 18.021881 - долгота и широта.

2022-02-18 20:21 UTC, AntePost commented on packages/backend/common/interfaces/accommodation-int.ts
> +export interface AccommodationInt {
У нас на фронте называется IAccomodation. Здесь можно также.

2022-02-18 20:22 UTC, AntePost commented on packages/backend/database/factories/ApartmentsFactory.ts
> +      bnovoId: Math.random() * (20000 - 10) + 10,
Я имею в виду, что это выражение: Math.random() * (20000 - 10) + 10 - это float, а не int.

2022-02-18 20:24 UTC, AntePost commented on packages/backend/database/migrations/1643866041779_accommodation_apartment.ts
> +      table.unique(['apartment_id', 'accommodation_id'])
Чтобы их сразу было видно, иначе глазу сложно различить между колонками и ключами.

Data Definition Language:
```
CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);
```

2022-02-23 23:25 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    return response.status(HttpCode.OK).json(creatingOkMsg(apartments))
Иван, ругается, просит void. Решила пока не заморачиваться.

2022-02-24 00:36 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +  public novoId!: number
Самое интересное, ошибок Адонис не выдавал и в базу не добавил лишнего (правда SQL бы не позволила, только не могу понять, почему ошибок не выдал?), поэтому и не заметила.

2022-02-24 00:54 UTC, lgmarch commented on packages/backend/app/Models/Apartment.ts
> +  public geoCoordinateX!: string
Иван, менять не стала, так как ты обещал посмотреть, почему у тебя в старой базе это string

2022-02-24 22:48 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +import { HttpCode } from '../../../common/constants/http-status-codes'
Привет! Прописала, не заработало почему-то. Вернула все назад.

2022-02-24 22:50 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    await request.validate(CreateApartmentValidator)
Не знаю, привыкла, что вначале объявления переменных, потом все действия.

2022-02-24 22:51 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    await request.validate(CreateApartmentValidator)
Проверка accommodation теперь в контроллере AccommodationController. Поменялась логика.

2022-02-24 23:00 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    await request.validate(CreateApartmentValidator)
Иван, у меня по типам не проходит это. Из-за enumService. В нем надо выкидывать ошибку, если в диапазон не попали, чтобы не было undefined. Блин, если я сейчас еще заморочусь обработкой ошибок, я никогда не закончу этот ПР. Давай это в другом ПР?

2022-02-24 23:05 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +      const accommodation = await Accommodation.create(item)
Иван, специально смотрела доки. Promisse.all, map и await  - стандартная ситуация. Логика такая: этот промис ждет выполнения всех await/promise...

2022-02-24 23:06 UTC, lgmarch commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const apartmentCreate = await Apartment.query().where('id', apartment.id).preload('accommodations')
Нет, не работает так. Как ни изголялась. :)

2022-02-25 06:38 UTC, AntePost approved these changes

2022-02-25 06:38 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const id: number = Number.parseInt(idFront)
Можно просто + писать перед конвертируемым значением.

И я обычно вместо front пишу req, но это дело вкуса.

2022-02-25 06:38 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +        .send(creatingErrMsg('error', `Incorrect syntax: ${id}`))
Ну это скорее не синтаксис, а значение некорректное.

2022-02-25 06:38 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    const idOfAccommodations = accommodations.map((p: { id: number }) => +p.id)
А что p значит? Просто интересно.

2022-02-25 06:38 UTC, AntePost commented on packages/backend/common/enums/AdminDistrictsOfMoscow.ts
> +}
Еще есть 2 округа в Новой Москве

2022-02-25 06:45 UTC, merged