table orders
rento2/rento2 pull request #16
Opened 2022-02-27 18:01 UTC by Pafnodeveloper

2022-02-28 18:02 UTC, AntePost requested changes

2022-02-28 18:02 UTC, AntePost commented on packages/backend/database/migrations/1643871523726_orders.ts
> +      table.bigInteger('apartment_id').unsigned().references('id').inTable('apartments').onDelete('CASCADE')
Это кстати опасная опция. Лучше restrict и удалять явно. Ну или продумывать в каждом случае, стоит ли писать.

В данном случае точно нельзя, так как если квартиру удалить из админки, потрутся все заказы из БД.

2022-03-01 06:28 UTC, Pafnodeveloper commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +    // const orderResp = await Order.query().where('apartment_id', apartmentId).preload('apartments')
Возможно захочется выдавать данные и по квартире, указанной в заказе. Хотя в ответе будет нечитаемая портянка в таком случае

2022-03-01 06:29 UTC, Pafnodeveloper commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +      const fixedPrice = apartmentInfo['$attributes']['price']
Меня забавляет такая возможность JS, надо будет - уберу

2022-03-01 06:32 UTC, Pafnodeveloper commented on packages/backend/app/Models/Orders.ts
> +import { Apartment } from '.'
Это автоимпорт так работает

2022-03-01 06:34 UTC, Pafnodeveloper commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +    // phone: schema.string({ trim: true }, [
Да, знаю, не мог подобрать правильный номер, чтобы пройти валидацию поэтому закомментил. Уже нашел правильный вариант +79165553535

2022-03-01 06:35 UTC, Pafnodeveloper commented on packages/backend/database/migrations/1643871523726_orders.ts
> +      table.bigInteger('apartment_id').unsigned().references('id').inTable('apartments').onDelete('CASCADE')
Так это логично, как могут остаться заказы на несуществующую квартиру?

2022-03-01 11:57 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +      const fixedPrice = apartmentInfo['$attributes']['price']
Дело вкуса. Идиоматично через точку запрашивать, с скобки - альтернативный вариант.

2022-03-01 11:58 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +    // const orderResp = await Order.query().where('apartment_id', apartmentId).preload('apartments')
Ок.

Это API, его напрямую никто смотреть не будет, поэтому можно туда добавлять данные спокойно.

2022-03-01 11:59 UTC, AntePost commented on packages/backend/app/Models/Orders.ts
> +import { Apartment } from '.'
Понял. Ну это не совсем очевидно, к тому же лучше единого стиля придерживаться.

2022-03-01 12:00 UTC, AntePost commented on packages/backend/database/migrations/1643871523726_orders.ts
> +      table.bigInteger('apartment_id').unsigned().references('id').inTable('apartments').onDelete('CASCADE')
Заказы нам надо будет хранить до бесконечности по умолчанию, так как это информация об оплате. А так кто-то случайно грохнул квартиру из админки и ушли все актуальные по ней заказы.

2022-03-04 06:40 UTC, AntePost requested changes

2022-03-04 06:40 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +    if (!isNaN(id)) {
Все-таки такие if else вложенные не очень выглядят. Лучше (псевдокод):
if (isNan) return

А дальше уже запрос в БД, если все ок.

2022-03-04 06:40 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +  public async destroy ({ request, response }: HttpContextContract): Promise<any> {
А с этим что?

2022-03-04 06:40 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +    is_deleted: schema.boolean()
Этого поля в запросе не будет.

2022-03-06 07:56 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +    const id: number = parseInt(request.param('id'), 10)
Типизация в данном случае лишняя, TS сам поймет, что это число.

2022-03-06 08:20 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +    payment_type: schema.enum(Object.values(Pay)),
```suggestion
    payment_type: schema.enum(Object.values(Pay) as Pay[]),
```

2022-03-06 08:22 UTC, AntePost commented on packages/backend/app/Models/Orders.ts
> +  public adults!: string
Это это поле и аналоги ниже должно быть не string, а number

2022-03-06 08:24 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +      // const newOrder = new Order()
В валидаторе оставил коммент, если там поправить, можно этим способом здесь делать.

2022-04-10 11:27 UTC, closed without merging