Review model
rento2/rento2 pull request #21
Opened 2022-03-29 18:18 UTC by Lukentui

https://trello.com/c/DGtFEKNZ

2022-03-29 18:33 UTC, AntePost reviewed
Контроллер в отдельном PR будешь делать?

2022-03-29 18:33 UTC, AntePost commented on packages/backend/database/migrations/1643872444191_reviews.ts
>        table.foreign('apartment_id').references('id').inTable('apartments')
Я в PG не очень ориентируюсь, тут не нужно `.notNullable()`?

2022-03-29 18:33 UTC, AntePost commented on packages/backend/database/migrations/1643872444191_reviews.ts
> +      table.text('comment').notNullable()
Надо будет у Макара уточнить, могут ли быть отзывы только с оценкой без текста.

2022-03-29 18:34 UTC, Lukentui commented on packages/backend/database/seeders/ReviewSeeder.ts
> +    await ReviewsFactory.with('apartment').createMany(20)
Да, он к ним квартиры тоже создаст, но я думаю нет смысла заморачиваться на этом

2022-03-29 18:35 UTC, AntePost commented on packages/backend/database/seeders/ReviewSeeder.ts
> +    await ReviewsFactory.with('apartment').createMany(20)
Если что, у меня была мысль вынести число создаваемых в сидере квартир в константу и генерировать apartmentId в других моделях через Math.random. Но мб неоправданные усилия.

2022-03-29 18:43 UTC, Lukentui commented on packages/backend/database/migrations/1643872444191_reviews.ts
> +      table.string('avatar', 255).notNullable()
в аватар я ваще, честно сказать не верю, имхо будет выпилино из ненадобностью, но пока так, да

2022-03-29 18:43 UTC, Lukentui commented on packages/backend/database/migrations/1643872444191_reviews.ts
> +      table.string('address', 255).notNullable()
+

2022-03-29 18:45 UTC, Lukentui commented on packages/backend/database/migrations/1643872444191_reviews.ts
> +      table.text('comment').notNullable()
спросил, отпишусь как будет известно

2022-03-29 18:54 UTC, AntePost commented on packages/backend/database/seeders/ReviewSeeder.ts
> +export default class ApartmentSeeder extends BaseSeeder {
Сюда еще нужен флаг developmentOnly.

2022-03-29 18:55 UTC, AntePost commented on packages/backend/database/seeders/ReviewSeeder.ts
> +export default class ApartmentSeeder extends BaseSeeder {
```suggestion
export default class ReviewSeeder extends BaseSeeder {
```

2022-03-30 19:04 UTC, Lukentui commented on packages/backend/database/seeders/ReviewSeeder.ts
> +    await ReviewsFactory.with('apartment').createMany(20)
угу, ну на подумать - да, но пока есть другие дела, я думаю

2022-03-30 19:22 UTC, AntePost requested changes

2022-03-30 19:22 UTC, AntePost commented on packages/backend/.eslintrc.json
> +    "comma-dangle": "off",
Ты на темной стороне Силы)

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +  public async list ({ response }: HttpContextContract): Promise<void> {
В list наверно нужно будет добавить пагинацию. Но может не в первую очередь.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +    const review = await Review.find(request.param('id', null))
id стоит провалидировать.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +    await request.validate(CreateReviewValidator)
А почему не используешь возвращаемое значение? Оно сразу типизировано.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +      return response.send(creatingErrMsg('error', 'Review not found'))
```suggestion
      return response.status(HttpStatusCode.NotFound).send(creatingErrMsg('error', 'Review not found'))
```

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +export default class ReviewsController {
Метода update не хватает.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +    return response.status(HttpStatusCode.OK).send(creatingOkMsg('OK', review.id))
```suggestion
    return response.status(HttpStatusCode.OK).send(creatingOkMsg('Review deleted', review.id))
```
Раз выше 'Review created'.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Validators/CreateReviewValidator.ts
> +      rules.regex(/^[a-zA-Z0-9-_. ]+$/)
100% будут кириллицей писать имя.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/app/Validators/CreateReviewValidator.ts
> +      rules.maxLength(5),
К number неприменимо: https://docs.adonisjs.com/reference/validator/rules/max-length. Там вот это нужно: https://docs.adonisjs.com/reference/validator/rules/range

2022-03-30 19:22 UTC, AntePost commented on packages/backend/start/routes/apartment.ts
> +Route.resource('api/v1/apartments', 'ApartmentsController').apiOnly()
Тогда может роуты не разбрасывать по разным файлам? Чтобы можно было всем один префикс назначить.

2022-03-30 19:22 UTC, AntePost commented on packages/backend/start/routes/review.ts
> +  .group(() => {
Формат не по классическому REST, но в целом ок, мне кажется.

2022-03-30 19:29 UTC, Lukentui commented on packages/backend/.eslintrc.json
> +    "comma-dangle": "off",
ты про лидирующую запятую или нестрогое сравнение?)

2022-03-30 19:30 UTC, Lukentui commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +  public async list ({ response }: HttpContextContract): Promise<void> {
ну я предлагаю отложить чуть на попозже, когда будет точно понятна какую пагинацию впилить туда лучше

2022-03-30 19:32 UTC, Lukentui commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +    const review = await Review.find(request.param('id', null))
не я не вижу тут смысла, честно говоря, ибо escape делает сама orm, а если осознано кто-то будет пытаться туда флудить большими данными - ну хз что он добьется. Зато у нас все просто красиво и читабельно

2022-03-30 19:33 UTC, Lukentui commented on packages/backend/start/routes/review.ts
> +  .group(() => {
угу, ну он чуть отличается да, но не страшно имхо

2022-03-30 19:39 UTC, AntePost commented on packages/backend/.eslintrc.json
> +    "comma-dangle": "off",
Про запятую. Про сравнение очень жесткое правило да, хотя там вроде можно кастомизировать.

2022-03-30 19:48 UTC, Lukentui commented on packages/backend/.eslintrc.json
> +    "comma-dangle": "off",
А, не-не, я не на темной, а на черной стороне)) я бы вообще сделал обязательной эту штуку, но у всех подряд посыпется

2022-03-30 20:27 UTC, Lukentui commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +export default class ReviewsController {
+

2022-03-30 20:29 UTC, Lukentui commented on packages/backend/database/migrations/1643872444191_reviews.ts
> +      table.text('comment').notNullable()
решили делать обязательным

2022-03-30 20:29 UTC, Lukentui commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    return response.status(HttpStatusCode.OK).send(creatingOkMsg(apartments))
сделал ok дефолтным

2022-03-31 07:12 UTC, AntePost approved these changes

2022-03-31 07:12 UTC, AntePost commented on packages/backend/app/Controllers/Http/ReviewsController.ts
> +      .send(creatingOkMsg(await Review.query().limit(20).preload('apartment')))
Тогда наверно limit можно убрать, так как сейчас нельзя будет достать дальнейшие из БД никак.

2022-03-31 07:16 UTC, AntePost commented on packages/backend/start/routes.ts
> +      .group(() => {
Сюда еще update надо вынести.

2022-03-31 19:43 UTC, Lukentui commented on packages/backend/app/Validators/CreateReviewValidator.ts
> +      rules.regex(/^[А-ЯЁ][а-яё]*$/)
Ну я предлагаю пока оставить кириллицу, а дальше решить, пока имхо нет смысла это решать - дальше будет виднее

2022-03-31 19:51 UTC, merged