long term card info added
rento2/rento2 pull request #25
Opened 2022-04-01 11:33 UTC by Cinium

2022-04-01 13:16 UTC, AntePost requested changes
package-lock точно менять не надо. У тебя npm старой версии. Нужна >=7

И рекомендую всегда смотреть что именно коммитишь, чтобы там были только осознанные изменения.

2022-04-02 15:34 UTC, natalya-vd reviewed
У иконок почистить fill, предусмотреть чтобы через пропсы передавались классы (1 или 2, смотри по обстоятельствам сколько нужно). Когда используешь уже у себя иконку, то прописываешь fill/stroke согласно макету

Не зашивай высоту через height, используй min-height (если нужно чтобы карточка была какого-то размера)

Параметры шрифтов везде прописать через миксины.

Выравнивание флексами прописать через глобальные классы в разметке компонента

Большая часть кнопок у нас будет забита через одну кнопку с вариантами выбора. Не нужно отдельно прописывать параметры для кнопок

Везде для типов используешь String, Number нужно по-другому, через примитивы https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types

Используй интерфейсы для указания типов (по большей части, но не везде это может быть оправдано) и выноси их в отдельные файлы, а потом подключай где нужно.

Отступ между иконкой и текстом не соответствует макету (слишком маленький).
Иконка с избранным будет в таком состоянии, если квартиру добавили в избранное, в обычном состоянии без цвета. Пока можешь оставить цвет как в макете. Но учитывай этот момент.
![image](https://user-images.githubusercontent.com/79200958/161390240-3dd4bb8c-3091-4e7b-9334-c15f9707481e.png)

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoAdress.tsx
> +      {adress.metro !== null ??
А зачем здесь эта проверка?
Ты здесь по сути говоришь если adress.metro !== null, то выведи пустоту иначе выведи то, что вернет map.

Собственно поэтому у тебя и не отображаются метро на странице.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
https://github.com/tc39/proposal-nullish-coalescing#syntax

Еще при сравнении с null можно использовать нестрогое сравнение, тогда одновременно проверишь на null и undefined

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoAdress.tsx
> +      {adress.metro !== null ??
А зачем здесь эта проверка?
Ты здесь по сути говоришь если adress.metro !== null, то выведи пустоту иначе выведи то, что вернет map.

Собственно поэтому у тебя и не отображаются метро на странице.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
https://github.com/tc39/proposal-nullish-coalescing#syntax

Еще при сравнении с null можно использовать нестрогое сравнение, тогда одновременно проверишь на null и undefined

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoButton.tsx
> +export const LongInfoButton = ({ text, classProp, onClick, children }: {
Не нужно прописывать кнопку. Возьмешь уже готовую.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoButton.tsx
> +export const LongInfoButton = ({ text, classProp, onClick, children }: {
Не нужно прописывать кнопку. Возьмешь уже готовую.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoDetails.tsx
> +    commission: String
Используй интерфейсы и выноси их в отдельные файлы, а потом подключай где нужно. У тебя этот пропс в нескольких местах, получается дублирование кода.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoDetails.tsx
> +    commission: String
Используй интерфейсы и выводи их в отдельные файлы, а потом подключай где нужно. У тебя этот пропс в нескольких местах, получается дублирование кода.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoParameters.tsx
> +      <li className={ classNames(styles['item']) }>
Я обычно классы для ul называю list, а для li item. Как-то понятнее: есть список ,а есть его пункт.

Но тут на твое усмотрение.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfoParameters.tsx
> +      <li className={ classNames(styles['item']) }>
Я обычно классы для ul называю list, а для li item. Как-то понятнее: есть список ,а есть его пункт.

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfo.tsx
> +      <a className={ classNames(styles['location']) }>
Поставь пока заглушку для href="#"

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfo.tsx
> +      <a className={ classNames(styles['location']) }>
Поставь пока заглушку для href="#"

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfo.tsx
> +        {price.toString() + ' / месяц'}
Здесь можно использовать шаблонную строку, выглядит симпатичнее, читать проще, особенно когда нужно склеить много данных.
```suggestion
        {`${price.toString()} / месяц`}
```
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2022-04-02 15:34 UTC, natalya-vd commented on packages/frontend/src/components/modules/LongInfo/LongInfo.tsx
> +        {price.toString() + ' / месяц'}
Здесь можно использовать шаблонную строку, выглядит симпатичнее, читать проще, особенно когда нужно склеить много данных.
```suggestion
        {`${price.toString()} / месяц`}
```
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2022-04-13 22:56 UTC, closed without merging