add backend support for admin
rento2/rento2 pull request #26
Opened 2022-04-02 16:02 UTC by TeemPresents

2022-04-02 16:09 UTC, AntePost requested changes
Подробнее гляну позже, пока скажу, что у тебя переписались package-lock из-за старой версии npm. Нужна >=7, чтобы не переписывала этот файл.

2022-04-04 08:19 UTC, AntePost commented on packages/admin/src/dataProvider/index.ts
> +    return await httpClient(url, options).then(({ headers, json }) => {
await в данном случае не нужен: https://purpleschool.ru/blog/return-await

2022-04-04 08:20 UTC, AntePost commented on packages/admin/src/dataProvider/index.ts
> +    await httpClient(`${apiUrl}/${resource}/${params.id}`).then(({ json }) => ({
Тут ты ничего не возвращаешь.

2022-04-04 09:15 UTC, SeehBall commented on packages/admin/package.json
> +    "typescript": "^4.6.3",
Нет, наоборот, пока не обновил, все крашилось

2022-04-04 09:16 UTC, SeehBall commented on packages/admin/package.json
> +    "ra-data-simple-rest": "^3.19.10",
Нет, удалю

2022-04-05 16:57 UTC, Lukentui commented on packages/admin/package.json
> +    "@typescript-eslint/parser": "^5.17.0",
да, убери в dev requirements

2022-04-05 16:58 UTC, Lukentui commented on packages/backend/config/cors.ts
> +  enabled: true,
зачем? корсы нам не нужны + этим должен управлять сервер, а не приложение

2022-04-05 17:17 UTC, Lukentui commented on packages/admin/src/dataProvider/index.ts
> +            'Content-Type': 'text/plain'
оно тут не нужно

2022-04-05 17:17 UTC, Lukentui commented on packages/admin/src/dataProvider/index.ts
> +        'Content-Type': 'text/plain'
аналогично

2022-04-05 17:27 UTC, Lukentui commented on packages/admin/src/dataProvider/index.ts
> +        total:
соответственно здесь будет значение из meta.pagination.count

2022-04-05 17:28 UTC, Lukentui commented on packages/admin/src/dataProvider/index.ts
> +        total:
аналогично

2022-04-05 17:29 UTC, Lukentui commented on packages/admin/src/dataProvider/index.ts
> +      countHeader === 'Content-Range'
зачем оно нужно? ты на бэке это поле захардкодил, могу предположить что ты не используешь это - нужно выпилить

2022-04-05 17:35 UTC, Lukentui commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +    response.header('access-control-expose-headers', 'content-range')
вот это нужно выпилить, причем оба.
Вместо этого нужно в creatingOkMsg добавить необязательный третий аргумент, который будет принимать любой объект, туда нужно прокидывать { pagination: { count: number } },
а в creatingResponse.ts сделать 

```ts
export function creatingOkMsg<U> (data: U, message: string = 'OK', meta: any = {}): IPositiveResponse<U> {
  return {
    meta: {
      result: message,
      ...meta
    },
    data: data === null ? [] : data
  }
}
```

2022-04-06 17:05 UTC, SeehBall commented on packages/backend/config/cors.ts
> +  enabled: true,
Иначе мне приходит с бэка ошибка корсов

2022-06-06 06:57 UTC, closed without merging