Orders model
rento2/rento2 pull request #32
Opened 2022-04-07 19:14 UTC by Lukentui

2022-04-07 19:23 UTC, AntePost reviewed
У orders не может быть update. Код можно отставить, только роут закомментировать.

Еще глянь гуглдок, который у нас в канале в закрепе, там обсуждались доработки по этой сущности.

2022-04-07 19:23 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +    paid_part: schema.number([
Это % от 0 до 100.

2022-04-07 19:23 UTC, AntePost commented on packages/backend/app/Models/Order.ts
> +  public isDeleted: boolean = false
Лучше поменять на deletedAt.

2022-04-08 06:59 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +    prices: schema.array().members(schema.number()),
Там не только цена, а день/цена должна быть, если я правильно помню. То есть [ {date, time} ].

2022-04-08 06:59 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
>      nights_number: schema.number([
Тогда тут тоже camelCase.

2022-04-08 08:14 UTC, AntePost requested changes
Пакеты точно нужно поправить.

2022-04-08 08:14 UTC, AntePost commented on package.json
> +  "dependencies": {
А зачем в корень? В backend надо.

2022-04-08 08:14 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +        .members({ date: schema.date(), price: schema.number() })
Я вот думаю, что в запросе DateTime ведь не передашь? Может написать регулярку для RFC 3339.

2022-04-08 08:38 UTC, Lukentui commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +        .members({ date: schema.date(), price: schema.number() })
я думаю нет смысла, либа все равно любой формат как надо распарсит, и date и datetime

2022-04-08 09:05 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +      await request.validate(CreateOrderValidator)
Вообще если он используется и в update, то это не CreateOrderValidator (и в других сущностях тоже). Но это так, просто нейминг, некритично.

2022-04-08 09:07 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +        .members({ date: schema.date(), price: schema.number() })
Я имею в виду, что это же классы JS, а в запросе мы будет строкой наверно передавать. Или timestamp.

2022-04-08 09:07 UTC, AntePost commented on packages/backend/app/Validators/CreateOrderValidator.ts
> +        .members({ date: schema.date(), price: schema.number() })
Или ты проверял, что корректно отработает, если datetime строку передать?

2022-04-09 08:36 UTC, AntePost approved these changes

2022-04-09 08:36 UTC, merged