Structure
rento2/rento2 pull request #45
Opened 2022-04-15 09:21 UTC by BrynzevDmitrii

Только структура

2022-04-18 19:06 UTC, BrynzevDmitrii commented
иконки пока не добовлял

2022-04-19 19:45 UTC, natalya-vd reviewed
Когда нажимаешь на пункт с договорами, появляется картинка с вопросом (нужно убрать отрисовку заголовка на основе пути). Зачем делать лишнию операцию по определению пути в родителе, если можно на основе пришедших данных (которые и так либо будут передаваться, либо нет) прописать условие?

Компонент AgreementsList не должен находиться в слое shared: нарушена логика подключения компонентов (мы не можем из widgets подключать в shared), и наврядли этот компонент будет где-то использоваться, кроме как для меню. Это должен быть виджет, который просто состоит из 2-х частей Tenants и Owners

Tenants и Owners лучше сделать одним компонентом.

Не называй так файлы (O&T.module.scss). Что значит O, а что T?

ButtonGeneral вернуть как была.

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/shared/ui/agreements-list/ui/Agreements.module.scss
> +.container {
Можно такие вещи называть wrapper, inner.
А то все будет в container)

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/shared/ui/agreements-list/ui/Agreements.module.scss
> +  &_contract {
По БЭМ элемент отделяется через 2 знака подчеркивания от блока.

Но здесь я бы выбрала другое название для блока. Иначе получается, что далее нужно будет везде привязываться к лову container, т.е.
container__contract
container__title

Если посмотреть на разметку с названиями классов они получаются в беспорядке: вроде блок у тебя container, а дальше у тебя идут названия классов не от блока.

В общем я думаю лучше переименовать классы.

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/shared/ui/agreements-list/ui/AgreementsList.tsx
> +import { Owners, Tenants } from '@widgets/documents-agreements'
Этого компонента в shared не должно быть

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-agreements/model/dataOwners .tsx
> +import { IPropsMenu } from '@widgets/documents-side-menu'
Здесь нарушается принцип, по-которому мы не можем импортировать что-то между слоями одного уровня, т.е. из разных компонентов из widgets в widgets

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-agreements/model/dataOwners .tsx
> +import { IPropsMenu } from '@widgets/documents-side-menu'
Когда такая ситуация, то лучше данные вынести на слой выше и передать через пропс или контекст, если вложенность большая (их бы и так лучше сверху передать)

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-agreements/ui/O&T.module.scss
> +.title-container {
Не называй так файлы O&T.module.scss. Что значит O, T. Используй полное название, сокращения только для чего-то общепринятого.
И если у тебя 2 компонента, то и файлы со стилями разбей на 2 файла, под каждый компонент.

2022-04-19 19:45 UTC, natalya-vd commented on packages/frontend/src/shared/ui/agreements-list/ui/AgreementsList.tsx
> +import { Owners, Tenants } from '@widgets/documents-agreements'
Нельзя импортировать из widgets в  shared, Нарушение feature-sliced

2022-04-21 07:17 UTC, patapiks commented on packages/frontend/src/widgets/documents-agreements/ui/ItemAgreements/ItemAgreements.tsx
> +              <Link href={ contract.href }>
Я видел, что на проекте реализован компонент GeneralLink, думаю нужно его переиспользовать!

2022-04-21 07:23 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
достаточно `titleText ? логика : логика`, а еще лучше `titleText && лоигка`

2022-04-21 07:35 UTC, natalya-vd commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
titleText строковое значение, как его можно применять для булевых значений? Разве будет так работать без ошибок со стороны ts?

2022-04-21 07:43 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Конечно, '' == false, else true.

2022-04-21 08:05 UTC, natalya-vd commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Если так сделать, то попадаешь на эту ошибку линта
https://github.com/typescript-eslint/typescript-eslint/blob/v4.0.1/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

2022-04-21 08:18 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Забавно, на мой взгляд это делает код намного лаконичнее. Ну ок.

2022-04-21 18:03 UTC, AntePost commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Фиговое правило, код реально лаконичнее. Ну можно !! сделать. Или погибче правило настроить, там есть опции.

2022-04-21 18:05 UTC, AntePost commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Или на length проверять.

2022-04-21 19:32 UTC, natalya-vd commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
@AntePost Насчет null не поняла. Вроде и так на null проверяется. Или что имел ввиду?

2022-04-21 19:55 UTC, secondwind612 commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Тогда titleText != null && лоигка.

Тогда в принципе ок, что правило такое. Лучше явно проверять, чем пропускать пустые строки.

2022-04-21 19:56 UTC, AntePost commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +        {titleText != null
Тогда titleText != null && лоигка.

Тогда в принципе ок, что правило такое. Лучше явно проверять, чем пропускать пустые строки.

2022-04-24 10:23 UTC, natalya-vd reviewed
Неправильно указаны данные договоров для Арендаторов и Собственников (поменять местами)

Нет ховера/фокуса для стрелки

И еще там есть доп. меню под это меню. Чуть позже отпишусь как должно быть. Напомни если забуду.

2022-04-24 10:23 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-agreements/ui/Agreements/AgreementsList.tsx
> +
И я бы назвала просто Agreements, т.к. AgreementsList в моем понимании когда есть 1 единица (li) и потом проходишься map и эту li вкладываешь в ul.

2022-04-24 10:23 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-agreements/ui/Agreements/AgreementsList.tsx
> +
И еще по названиям старайся именовать единообразно в плане у тебя есть 2 компонента один называешь AgreementsList, а другой ItemAgreements (т.е. меняешь местами слово Agreements). Но это мое видение, могу быть неправа.

2022-04-27 19:59 UTC, patapiks commented on packages/frontend/src/pages-fs/docs/agreements/AgreementsPage.tsx
> +  const titleText = 'Образцы документов'
Нужно вынести переменную за пределы компонента, чтобы она не определялась заново на каждом рендере.

2022-04-27 19:59 UTC, patapiks commented on packages/frontend/src/pages-fs/docs/faq/FaqPage.tsx
> +  const titleText = 'Частые вопросы'
Аналогично.

2022-04-27 19:59 UTC, patapiks commented on packages/frontend/src/widgets/documents-agreements/ui/Agreements/AgreementsList.tsx
> +import style from './Agreements.module.scss'
Стили, а не стиль.

2022-04-28 17:41 UTC, mashahori requested changes

2022-04-28 17:41 UTC, mashahori commented on packages/frontend/src/widgets/documents-agreements/ui/AgreementsItems/AgreementsItem.tsx
>              <li key={ idx }
Индекс не рекомендуется класть в key

2022-04-28 17:41 UTC, mashahori commented on packages/frontend/src/widgets/documents-agreements/ui/AgreementsItems/AgreementsItem.tsx
> +              <LinkGeneral classProps={ style['a'] }
Лучше называть классы в соответствии с элементом, на который они навешаны. Например item__link

2022-04-30 05:49 UTC, BrynzevDmitrii commented on packages/frontend/src/widgets/documents-agreements/ui/AgreementsItems/AgreementsItem.tsx
>              <li key={ idx }
Ок, как тогда лучше?

2022-04-30 18:31 UTC, mashahori commented
Ховер крестика немного не такой, как в макете 
![image](https://user-images.githubusercontent.com/39410999/166117859-f890c221-69b9-48de-bb97-9f22ef216149.png)
![image](https://user-images.githubusercontent.com/39410999/166117873-1cd68d87-0850-4c63-a1a8-32ecf62911a4.png)

Еще кажется что-то с отступами слева/справа на мобильной версии. Нужно сверить соответствует ли страница макету на каждом разрешении экрана.

2022-05-05 19:52 UTC, BrynzevDmitrii commented
Кликабельна пока только "Договор долгосрочной аренды жилого помещения" , аккардеон вставил просто чтобы небыло пусто. Данные для акардионов будм брать у Андрея.

2022-05-06 12:04 UTC, patapiks commented on packages/frontend/src/pages-fs/docs/agreements-long/AgreementsLongPage.tsx
> +        widthProps={ 1060 }
Предлагаю всю эту статику вынести в отдельный файл!!!

2022-05-06 12:04 UTC, patapiks commented on packages/frontend/src/pages-fs/docs/agreements-long/AgreementsLongPage.tsx
> +        titleIcon='/images/docs/agreements-treaty.svg'
Это точно название иконки?

2022-05-06 12:06 UTC, patapiks commented on packages/frontend/src/shared/ui/accordions/accordion-base/Accordion.module.scss
> +      div {
Danger

2022-05-06 12:11 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +  titleIcon?: string|undefined
То что он необязательный уже подразумевает возможность undefined, поэтому думаю просто string.

2022-05-06 12:13 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +export function DocumentsLayout ({ titleText, children, widthWindowProps, sideMenu, headMenu, widthProps, titleIcon, update }: IDocumentsLayout): JSX.Element {
Очень длинная портянка.. Я бы объявил как `(props: IDocumentsLayout)`, а внутри комопнента деструктурировал:
```
const { titleText, children, widthWindowProps, sideMenu, headMenu, widthProps, titleIcon, update } = props
```

2022-05-06 12:14 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +    <div className={ classNames(styles['flex-wrapper'], 'container-old') }>
container-old, звучит как что-то не актуальное, может стоит сразу заменить?

2022-05-06 12:14 UTC, patapiks commented on packages/frontend/src/shared/ui/documents-layout/DocumentsLayout.tsx
> +
Лишняя строка.

2022-05-06 12:17 UTC, patapiks commented on packages/frontend/src/widgets/docs-title/ui/DocsTitle.tsx
> +}
<s>undefined</s>

2022-05-06 12:17 UTC, patapiks commented on packages/frontend/src/widgets/docs-title/ui/DocsTitle.tsx
> +  titleText?: string|number|undefined
titleText может быть number?

2022-05-06 12:19 UTC, patapiks commented on packages/frontend/src/widgets/docs-title/ui/DocsTitle.tsx
> +
Лишняя строка.

2022-05-06 12:20 UTC, patapiks commented on packages/frontend/src/widgets/docs-title/ui/DocsTitle.tsx
> +    case 'Частые вопросы':
Все кейсы известны? Нужно вынести их в константы!!

2022-05-06 12:27 UTC, patapiks commented on packages/frontend/src/widgets/docs-title/ui/DocsTitle.tsx
> +  switch (titleText) {
Я бы написал функцию 
```
const renderDocTitle = (titleText) => {
  свич....
}

return (
<div className={ styles['title'] }>
          <h1 className={ styles['title__text'] }>
            {titleText}
          </h1>
          {renderDocTitle()}
</div>
)
```

2022-05-06 12:28 UTC, patapiks commented on packages/frontend/src/widgets/documents-agreements/model/dataTenants.tsx
> +
Лишняя строка.

2022-05-06 12:34 UTC, patapiks commented on packages/frontend/src/widgets/documents-agreements/ui/AgreementsItems/AgreementsItem.tsx
>              <li key={ idx }
Что в contract лежит, если нет ничего уникального, сделай. Типа `key={ contract.href + contract.title }`.

2022-05-06 12:35 UTC, patapiks commented on packages/frontend/src/widgets/documents-side-menu/lib/type/IPropsMenu.tsx
> +  // тут еще подумаю,может быть сделать отдельный интерфейс? или это нормальная практика?
Вопросы в чате!! В коде не нужно!!

2022-05-06 12:36 UTC, patapiks commented on packages/frontend/src/widgets/documents-side-menu/model/dataMenu.tsx
> +
Проверь все файлы на лишние строки. Больше не буду тыкать)

2022-05-06 12:37 UTC, patapiks commented on packages/frontend/src/widgets/documents-side-menu/ui/SideMenu/AgreementsSideMenu.tsx/AgreementsSideMenu.tsx
> +export const AgreementsSideMenu = ({ data, activeItem }: {data: IPropsAgreements, activeItem: string}): JSX.Element => {
Вынести тип в интерфейс.

2022-05-06 12:38 UTC, patapiks commented on packages/frontend/src/widgets/documents-side-menu/ui/SideMenu/AgreementsSideMenu.tsx/AgreementsSideMenu.tsx
> +          <li className={ styles['comback-buton'] }>
ul => li => a

2022-05-07 07:38 UTC, BrynzevDmitrii commented on packages/frontend/src/pages-fs/docs/agreements-long/AgreementsLongPage.tsx
> +        widthProps={ 1060 }
> Предлагаю всю эту статику вынести в отдельный файл!!!

Не понял твоего предложения. Это ведь все пропсы для компонента DocumentsLayout. Покажи плз пример, как это должно выглядеть.

2022-05-12 22:03 UTC, natalya-vd reviewed
Проверить типы ts (можно командой npx tsc --noEmit чтобы в консоль вывело, а не заходить в каждый файл и смотреть где подсвечивает). Есть расхождения. Исправить.
Смотри на подсветку редактора.

В файлах с модулями scss нужно дописать импорт файлов.

2022-05-18 16:21 UTC, natalya-vd commented on packages/frontend/src/pages-fs/docs/agreements-long/AgreementsLongPage.tsx
>  import { dataAgreementsTenants, HeadMenu, SideMenu } from '@widgets/documents-side-menu'
Этот файл нужно удалить. Текст договора уже сделал Андрей и с его веткой зальем.
В твоей ветке нужно сделать как в девелоп в этой папке.

2022-05-18 16:29 UTC, natalya-vd commented on packages/frontend/src/shared/ui/accordions/accordion-base/Accordion.module.scss
> +    // &:hover
Не забывай удалять неиспользуемый код. Таких комментариев не должно быть

2022-05-18 16:31 UTC, natalya-vd commented on packages/frontend/src/shared/ui/index.ts
> +export * from '../../widgets/documents-layout/DocumentsLayout'
А это что здесь делает? Это публичное АПИ для комопнентов из shared слоя!

2022-05-18 16:37 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-layout/DocumentsLayout.tsx
> +import { DocsTitle } from '@widgets/documents-layout/docs-title'
Здесь импорт должен быть из другого места, а packages\frontend\src\widgets\documents-layout\docs-title\index.ts нужно удалить

2022-05-18 16:38 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-layout/docs-title/ui/DocsTitle.tsx
> +  update: string|number|undefined
А зачем здесь undefined? Предполагается, что эти значения будут необязательные? Тогда через знак "?"

2022-05-18 16:38 UTC, natalya-vd commented on packages/frontend/src/widgets/documents-layout/docs-title/ui/DocsTitle.tsx
> +  function DocsSwich (title: any): JSX.Element {
any не должно быть. Пиши конкретный тип. Выше строчкой тоже самое

2022-06-01 21:07 UTC, natalya-vd approved these changes

2022-06-02 17:01 UTC, mashahori approved these changes

2022-06-02 18:12 UTC, merged