Rimidalu/subway station to line
rento2/rento2 pull request #46
Opened 2022-04-16 09:59 UTC by RimidalU

Добавляет название линии метро по станции в БД.

2022-04-17 09:37 UTC, AntePost requested changes
У тебя много замечаний от линта, но я не могу их локально воспроизвести. Тебе надо использовать наши настройки линта, чтобы он не переделывал стиль. Иначе постоянно будем друг друга менять. И ревьюить сложно.

2022-04-17 09:37 UTC, AntePost commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string
Поскольку мы не обращаемся к api для получения станции, можно сделать ее пока виртуальным полем, чтобы не хранить в БД.

2022-04-17 09:37 UTC, AntePost commented on packages/backend/common/helpers/subwayStationToLine.ts
> +    return 'These stations are not in our bases'
Сейчас это значение запишется в БД. Мне кажется лучше возвращать null, а это сообщение логировать.

2022-04-20 06:55 UTC, RimidalU commented on packages/backend/common/helpers/subwayStationToLine.ts
> +    return 'These stations are not in our bases'
точно. переделаю

2022-04-20 11:13 UTC, RimidalU commented on packages/backend/common/helpers/subwayStationToLine.ts
> +    return 'These stations are not in our bases'
логировать не стал - сделаю потом под конкретную надпись, что бы не переделывать

2022-04-20 11:17 UTC, AntePost commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string | null
Хм, ! как раз означает, что не может быть null. Это требование ORM. Интересно, как это будет работать.

2022-04-20 11:17 UTC, AntePost commented on packages/backend/common/interfaces/IApartment.ts
> +  subway_line: string | null
Теоретически можно сделать просто опциональным поле ?. Но тогда и undefined там может быть. Когда явно null - лучше.

2022-04-20 11:17 UTC, AntePost commented on packages/backend/common/helpers/subwayStationToLine.ts
> +    return 'These stations are not in our bases'
В смысле под конкретную надпись?

2022-04-20 11:21 UTC, RimidalU commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string | null
![image](https://user-images.githubusercontent.com/81852394/164219680-a7194254-bc25-4673-ba40-d407b7fa2784.png)
![image](https://user-images.githubusercontent.com/81852394/164219768-4650a795-defc-46b1-90a4-763d957819bb.png)

2022-04-20 11:23 UTC, RimidalU commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string | null
Когда не знаешь, что не должно так работать, то работает ))))

2022-04-20 11:27 UTC, RimidalU commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string | null
если убрать !, то ругается:   
Property 'subwayLine' has no initializer and is not definitely assigned in the constructor.ts(2564)

2022-04-20 16:28 UTC, RimidalU commented on packages/backend/common/interfaces/IApartment.ts
> +  subway_line: string | null
я первоначально сделал это поле optional в валидаторе, но начал ругаться ts, что у меня значение может быть undefined.  тогда я там поставил nullableAndOptional

2022-04-20 16:36 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +      Logger.warn(`'${apartmentPayload.subway_station}' stations are not in our bases`)
Тут вопрос, где писать сообщение в логи. Может внутри самой функции, так как она по сути не отработало. Но можно и тут наверно.

2022-04-20 16:40 UTC, RimidalU commented on packages/backend/common/helpers/subwayStationToLine.ts
> +    return 'These stations are not in our bases'
добавил

2022-04-20 16:40 UTC, AntePost commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +      Logger.warn(`'${apartmentPayload.subway_station}' stations are not in our bases`)
Моя логика в том, что где бы эту функцию не использовали, если она не нашла метро, надо это залогировать. Поэтому логичней внутри функции.

2022-04-20 16:41 UTC, RimidalU commented on packages/backend/app/Models/Apartment.ts
> +  public subwayLine!: string
обсудили в дискорде

2022-04-20 16:58 UTC, RimidalU commented on packages/backend/app/Controllers/Http/ApartmentsController.ts
> +      Logger.warn(`'${apartmentPayload.subway_station}' stations are not in our bases`)
инкапсуляция - логично. переделаю

2022-04-20 17:05 UTC, AntePost approved these changes

2022-04-20 17:05 UTC, merged