add login and logout logic
rento2/rento2 pull request #47
Opened 2022-04-17 11:33 UTC by TeemPresents

2022-04-17 11:47 UTC, AntePost requested changes
packages/frontend/package-lock.json переписался.

2022-04-17 11:47 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
> +      `${String(process.env['REACT_APP_SERVER_URL'])}/auth/login`, {
Конвертация в строку из-за линтера?

2022-04-17 11:47 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
> +    cookies.set('expires_at', data.data.expires_at)
У самих cookie есть lifetime уже, можно им задавать. https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie

2022-04-17 11:47 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
> +    if (cookies.get('token') === null) {
undefined не может вернуть?

2022-04-17 11:47 UTC, AntePost commented on packages/admin/src/components/LoginPage/LoginPage.tsx
> +import './styles.css'
Лучше назвать LoginPage.styles.css

У у нас тут less вроде используется.

2022-04-17 11:47 UTC, AntePost commented on packages/admin/src/components/LoginPage/styles.css
> +.raLogin-main {
А готовые компоненты нельзя кастомизировать? Я не против стилей, но вроде тут уже есть весь нужный UI.

2022-04-17 11:47 UTC, AntePost commented on packages/backend/config/cors.ts
> +  enabled: true,
@Lukentui, ты вроде был против, чтобы их включать?

2022-04-17 11:47 UTC, AntePost commented on packages/backend/docker-compose.yaml
> -      - ./_docker/data/postgres:/data/postgres
Удали тогда эту папку и убери из .gitignore упоминание.

2022-04-17 11:49 UTC, AntePost reviewed
Еще вот такая есть библиотека, если что: https://www.npmjs.com/package/react-cookie

2022-04-17 12:08 UTC, TeemPresents commented on packages/admin/src/common/authProvider.ts
> +      `${String(process.env['REACT_APP_SERVER_URL'])}/auth/login`, {
Да, он ругается иначе

2022-04-17 12:09 UTC, TeemPresents commented on packages/admin/src/common/authProvider.ts
> +    if (cookies.get('token') === null) {
На сколько я знаю нет, но и на него тоже проверю

2022-04-17 12:12 UTC, TeemPresents commented on packages/admin/src/components/LoginPage/styles.css
> +.raLogin-main {
Отдельный инпут не получается костомизировать

2022-04-17 12:20 UTC, TeemPresents commented on packages/backend/config/cors.ts
> +  enabled: true,
Забыл обратно переключить когда комитил

2022-04-17 13:22 UTC, AntePost requested changes
Cookie надо задать корректные настройки секьюрности. Посмотри те ссылки, которые я вчера скидывал.

2022-04-17 13:22 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
> +    if (cookies.get('access_token') === null || cookies.get('access_token') === undefined) {
Это можно проще проверить `== null`

2022-04-23 09:53 UTC, AntePost requested changes
Посмотри еще раз цепочку действий, которые тебе надо делать в middleware. И когда будешь тестировать, проверь все варианты, чтобы не пропускал с невалидной авторизацией.

2022-04-23 09:53 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
>      return await Promise.resolve()
await перед return лишний.

2022-04-23 09:53 UTC, AntePost commented on packages/admin/src/common/authProvider.ts
> +    return await Promise.resolve()
Хм, получается, да, мы же на бэке проверяем. И нормально работает? Без авторизации не пускает куда не надо?

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('access_token', token.accessToken, { expires: new Date(String(token.expiresAt)) })
А где ты задаешь, что http_only? И нужно ее еще secure сделать.

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('refresh_token', token.refreshToken)
А где ты возвращаешь response?

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('access_token', token.accessToken, { expires: new Date(String(token.expiresAt)) })
В принципе мы здесь luxon используем вместо date. Здесь некритично, но ради единообразия можно.

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
> +    const expireTime = new Date(cookies['Expires'])
И здесь.

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
> +    const expireTime = new Date(cookies['Expires'])
Ты по всем cookies проверяешь? И если хотя одна проходит, то пропускаешь?

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
>        return await next()
await не нужен.

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
> +  public async handle ({ auth, response, request }: HttpContextContract, next: () => Promise<void>): Promise<void> {
А где ты проверяешь, что это валидные токены?

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
> +    if (!(Date.now() <= expireTime.getTime())) {
Так это же одно и тоже условие.

2022-04-23 09:53 UTC, AntePost commented on packages/backend/app/Middleware/JWTAuth.ts
> +    } else {
И else необязательно, можно было как раньше, ты же делаешь return в if.

2022-04-23 10:30 UTC, TeemPresents commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('refresh_token', token.refreshToken)
Зачем возвращать response, если на фронте мы не работаем с куками, а только на сервере их задаем?

2022-04-23 10:32 UTC, AntePost commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('refresh_token', token.refreshToken)
Мы не работает с куками на фронте, но хранятся они на фронте.

2022-04-23 10:43 UTC, TeemPresents commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('access_token', token.accessToken, { expires: new Date(String(token.expiresAt)) })
В expires ругается, что должен быть тип Date

2022-04-23 11:19 UTC, AntePost commented on packages/backend/app/Controllers/Http/AuthController.ts
> +    response.cookie('access_token', token.accessToken, { expires: new Date(String(token.expiresAt)) })
https://moment.github.io/luxon/api-docs/index.html#datetimetojsdate=

2022-04-24 09:42 UTC, closed without merging