add icons
rento2/rento2 pull request #48
Opened 2022-04-18 16:48 UTC by natalya-vd

2022-04-18 18:33 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/filied/IconBus.tsx
> +  return (
Нужна ли эта строчка?

2022-04-18 19:31 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/filied/IconBus.tsx
> +  return (
А как без нее?

2022-04-18 19:53 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/filied/IconBus.tsx
> +  return (
```
export const IconBus = (props: IIconClassProps): JSX.Element => (
    <svg className={ classNames(styles['icon-filied'], props.classProps) }
      height="16"
      viewBox="0 0 16 16"
      width="16"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M2.66669 10.6666C2.66669 11.2533 2.92669 11.78 3.33335 12.1466V13.3333C3.33335 13.7 3.63335 14 4.00002 14H4.66669C5.03335 14 5.33335 13.7 5.33335 13.3333V12.6666H10.6667V13.3333C10.6667 13.7 10.9667 14 11.3334 14H12C12.3667 14 12.6667 13.7 12.6667 13.3333V12.1466C13.0734 11.78 13.3334 11.2533 13.3334 10.6666V3.99998C13.3334 1.66665 10.9467 1.33331 8.00002 1.33331C5.05335 1.33331 2.66669 1.66665 2.66669 3.99998V10.6666ZM5.00002 11.3333C4.44669 11.3333 4.00002 10.8866 4.00002 10.3333C4.00002 9.77998 4.44669 9.33331 5.00002 9.33331C5.55335 9.33331 6.00002 9.77998 6.00002 10.3333C6.00002 10.8866 5.55335 11.3333 5.00002 11.3333ZM11 11.3333C10.4467 11.3333 10 10.8866 10 10.3333C10 9.77998 10.4467 9.33331 11 9.33331C11.5534 9.33331 12 9.77998 12 10.3333C12 10.8866 11.5534 11.3333 11 11.3333ZM12 7.33331H4.00002V3.99998H12V7.33331Z" />
    </svg>
  )
```

2022-04-18 20:13 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesFigure = styles[`${figure}`] ?? ''
О чем говорит это выражение? Почему `figure` приводится к строке, если уже протипизирован?

2022-04-18 20:14 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const size = figure !== 'none'
size как boolean мм.. может тогда уже isSize?

2022-04-18 20:16 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/linear/IconClose.tsx
> +  // <svg className={ classNames(styles['icon'], props.classProps) }
Если не удаляешь, то желательно оставлять комментарий.

2022-04-18 20:16 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesFigure = styles[`${figure}`] ?? ''
ts ругается)

2022-04-18 20:17 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/linear/IconClose.tsx
> +  // <svg className={ classNames(styles['icon'], props.classProps) }
О, сенкс. Забыла)

2022-04-18 20:49 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesSize = styles['tick-figure'] ?? ''
Про смысл, выражения чуть ниже имел ввиду, мы обращаемся по конкретному ключу, в данном случае 'tick-figure', но его там может не быть?

2022-04-18 21:55 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesSize = styles['tick-figure'] ?? ''
Не совсем понимаю про какой смысл ты говоришь. Но идея здесь в том, что здесь иконка галки, но в макете у нас есть галка обведенная кругом и галка обведенная квадратом со закруглениями. Чтобы не плодить иконки я из одной делаю 3: предполагается в нее передавать какое значение фигуры нужно, а обводку рисовать css. Из-за рисования обводки размер исходной иконки нужно менять, поэтому есть size, которого в обычном состоянии не будет в дефолтной иконке.

Есть несколько таких иконок: плюс, крестик.

2022-04-18 22:25 UTC, patapiks commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesSize = styles['tick-figure'] ?? ''
8 строка оператор нулевого слияния: ЕСЛИ `styles['tick-figure']` содержит null или undefined ТО верни `''`, ИНАЧЕ верни `styles['tick-figure']`
Вопрос, в каком случае `styles['tick-figure']` может быть null или undefined?

2022-04-19 15:55 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesSize = styles['tick-figure'] ?? ''
Такой вопрос: откуда берется styles и что будет, если вдруг в styles не окажется 'tick-figure'?
Или я совсем не понимаю о чем ты?!? И что предлагаешь...

2022-04-19 16:34 UTC, AntePost commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  const stylesSize = styles['tick-figure'] ?? ''
У нас жестко настроен TS и не до конца настроена типизация CSS. Поэтому не можем гарантировать на уровне статического анализа, что в styles будет нужное. Кстати настроить типизацию CSS - неплохая задача, поможет упростить код.

2022-04-19 16:35 UTC, AntePost requested changes

2022-04-19 16:39 UTC, natalya-vd commented on packages/frontend/src/shared/ui/icons/linear/IconTick.tsx
> +  console.log(styles['test'])
Аааа. Забыла убрать)
Спасибо)

2022-04-19 16:55 UTC, AntePost approved these changes

2022-04-19 16:55 UTC, merged