gallery slider added
rento2/rento2 pull request #65
Opened 2022-05-06 17:59 UTC by Cinium

2022-05-06 18:27 UTC, patapiks commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.module.scss
> +  transition: all 0.3s;
transition: all  - не есть хорошо! Укажи те свойства которым нужен transition.

2022-05-06 18:35 UTC, patapiks commented on packages/frontend/src/shared/ui/buttons/ButtonIcon.tsx
> +  refProp?: LegacyRef<HTMLButtonElement>
Почему legacy? Мб RefObject!?

2022-05-07 08:28 UTC, Cinium commented on packages/frontend/src/shared/ui/buttons/ButtonIcon.tsx
> +  refProp?: LegacyRef<HTMLButtonElement>
Может быть)) коллеги со стаковерфлоу сказали так, а я не сопротивлялся
Поменял

2022-05-07 08:29 UTC, Cinium commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.module.scss
> +  transition: all 0.3s;
Да тут вообще он не нужен, хз зачем добавил

2022-05-07 12:21 UTC, mashahori requested changes

2022-05-07 12:21 UTC, mashahori commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.tsx
> +import 'swiper/css/thumbs'
Эти стили уже ипортируются глобально в index

2022-05-07 12:21 UTC, mashahori commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.module.scss
> +  max-width: 744px;
Мы же используем БЭМ вроде как

2022-05-07 12:21 UTC, mashahori commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.module.scss
> +  -webkit-tap-highlight-color: transparent;
А это для чего? почему с префиксом?

2022-05-07 13:09 UTC, Cinium commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.tsx
> +import 'swiper/css/thumbs'
Разве? Не могу найти
Да и галлерея вся ломается, если их убрать

2022-05-07 13:10 UTC, Cinium commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.module.scss
> +  -webkit-tap-highlight-color: transparent;
Это чтоб при тапах на элементы голубенького оверлея не возникало)) у нас же всё равно прописано у кнопок поведение при нажатии
Мой личный заскок, могу убрать

2022-05-07 13:19 UTC, patapiks commented on packages/frontend/src/widgets/gallery-slider/GallerySlider.tsx
> +import 'swiper/css/thumbs'
git pull origin develop

2022-05-11 08:28 UTC, mashahori submitted a review, later dismissed

2022-05-11 21:11 UTC, natalya-vd reviewed
Листание нижнего слайдера не нравится. Когда перелистываешь на 4 фотку (видимо предпоследнюю), то он резко делает ее первой в очереди. Ф думаю лучше будет, если просто все будет сдвигаться влево.

А индикатор (26/28) с числом слайдов не делал?

2022-05-12 22:46 UTC, natalya-vd reviewed
Файл с галереей и стилями к ней есть в корне виджета и в папке ui, какой правильный?

Нужно в файлах со стилями прописать импорты для переменных и миксинов.

Почему-то не работает экспорт из файла index.ts. Работает если прописать 
``export { GallerySlider } from './ui/GallerySlider'``

2022-05-13 21:17 UTC, natalya-vd approved these changes

2022-05-13 21:17 UTC, merged