Rimidalu/adonis5 swagger
rento2/rento2 pull request #71
Opened 2022-05-14 15:29 UTC by RimidalU

2022-05-14 16:59 UTC, AntePost requested changes

2022-05-14 16:59 UTC, AntePost commented on packages/backend/docs/swagger/Apartmens.yml
> +          description: "Fields for filter. Specify the displayed fields. example: purity, bnovo_id, description"
```suggestion
          description: "Fields for filter. Specify the displayed fields. For example: purity, bnovo_id, description"
```

2022-05-15 10:04 UTC, RimidalU commented on packages/backend/docs/swagger/Apartmens.yml
> +          description: "Fields for filter. Specify the displayed fields. example: purity, bnovo_id, description"
Исправил.

2022-05-15 11:01 UTC, AntePost approved these changes

2022-05-15 11:01 UTC, merged