notifications for successful orders
rento2/rento2 pull request #86
Opened 2022-06-11 10:07 UTC by RimidalU

2022-06-11 10:50 UTC, AntePost requested changes

2022-06-11 10:50 UTC, AntePost commented on packages/backend/app/Controllers/Http/OrdersController.ts
> +    await mailingOrderMessage(order)
Повесь на него catch, чтобы писал понятное сообщение в логах и саму ошибку выводил.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +      `https://api.telegram.org/bot${this.config.test_token}${path}`
```suggestion
      `https://api.telegram.org/bot${this.config.telegram_bot_token}${path}`
```

2022-06-11 10:50 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    return (
Лишние скобки.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +  from: ${dateFrom},
Здесь лучше по-русски написать, чтобы было удобнее читать получателю.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    return await this.sendMsgToTelegram(msg)
Неправильное разделение ответственности. sendMsgToTelegram не должен вызываться в createMessageBody. Наоборот можно в sendMsgToTelegram вызывать createMessageBody и sendRequest.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/common/helpers/mailingOrderMessage.ts
> +export async function mailingOrderMessage (order: InstanceType<Order>): Promise<void> {
mail order - это по-английски "посылка по почте". Я не очень понимаю предназначение этого класса. Вообще у нас цепочка следущая: запрос приходит в контроллер, контроллер вызывает сервисы. И вот внутри сервиса обработки ордеров нужно как раз и вызвать бронирование в bnovo (зависимость лучше передать через встроенный в Adonis IoC) и в случае успеха вызвать отправку сообщений в ТГ.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/common/helpers/mailingOrderMessage.ts
> +  class NewBnova extends Bnovo {
```suggestion
  class NewBnovo extends Bnovo {
```

Но вообще так переопределять классы внутри хелперов не очень хорошая практика.

2022-06-11 10:50 UTC, AntePost commented on packages/backend/config/telegram.ts
> +  test_token: Env.get('TEST_TELEGRAM_TOKEN'),
Для того env и существует, чтобы ты по одному и тому же ключу на локалке получал тестовое значение, а в проде - реальное. Тестовые ключи создавать не надо.

2022-06-24 07:06 UTC, AntePost requested changes

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
>  class TelegramBot {
Аналогично по этому классу.

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    ).ok;
А если не ок?

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    const msg =encodeURIComponent(`
```suggestion
    const msg = encodeURIComponent(`
```
Этот метод для шифровки URL, а не тела.

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +      с ${dateFrom.toLocaleString()} по ${dateTo.toLocaleString()}.
Учитывай часовые пояса еще. На сервере будет UTC скорее всего. Можешь воспользоваться luxon для того, чтобы по МСК выставить.

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +      Cсылка на оплату:${payment_url}
```suggestion
      Cсылка на оплату: ${payment_url}
```

2022-06-24 07:06 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    return await this.sendMsgToTelegram(msg);
```suggestion
    return this.sendMsgToTelegram(msg);
```
Если это функция createMessageBody, то непонятно, почему она вызывает sendMsgToTelegram. Почитай про single responsibility principle. Там про классы, но к функциям это тоже можно отнести.

2022-06-24 07:06 UTC, AntePost commented on packages/backend/common/interfaces/IOrderServices.ts
> +export interface IpaidOrder {
Название файла и экспортируемой переменной не совпадают.

2022-06-24 07:06 UTC, AntePost commented on packages/backend/common/interfaces/Itelegram.ts
> +export interface ItelegramConfiguration {
Аналогично.

2022-06-25 07:30 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +    if (response) {
все ответы через обьект возвращаются
![image](https://user-images.githubusercontent.com/81852394/175763465-36a6a0c2-7db2-4bb4-8f4a-5f40b59a468c.png)

2022-06-25 07:56 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +    const msg =encodeURIComponent(`
я исходил из этого:
https://stackoverflow.com/questions/332872/encode-url-in-javascript
![image](https://user-images.githubusercontent.com/81852394/175764147-739d299f-605c-4ffd-ab0d-5209f0b4eb2e.png)

так как этот метод наиболее всеяден, а какие символы могут быть в ссылке на оплату я на нашёл.

2022-06-25 12:19 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +    if (response) {
Тогда зачем проверять, что response существует?

2022-06-25 12:21 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    const msg =encodeURIComponent(`
Все, увидел выше, что это не тело, а query param. Посмотри, может axios это уже сам делает, тогда не нужно. Если нет, то да, нужно.

2022-06-25 17:24 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +    ).ok;
тогда хреново)) Исправил.

2022-06-25 17:47 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +    const newBnovo = new Bnovo();
Сделал.

2022-06-25 17:48 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +export const orderServices = new OrderServices();
Переделал

2022-06-25 17:48 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +    return await this.sendMsgToTelegram(msg);
Исправил.

2022-06-25 18:18 UTC, AntePost requested changes

2022-06-25 18:18 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +  newBnovo
```suggestion
  bnovo
```

2022-06-25 18:18 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +    if (response) {
Тут остается вопрос.

2022-06-25 18:18 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +
```suggestion
```

2022-06-25 18:18 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +      const error = err as Error
```suggestion
      if (error instanceof Error) {
            const error = err as Error
      }
```

Ты где-то логируешь ошибку, если не удалось забронировать или не удалось отправить уведомление в ТГ? Надо.

2022-06-25 20:16 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +  newBnovo
сделал

2022-06-25 20:20 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +
добавил try-catch

2022-06-25 20:32 UTC, AntePost requested changes

2022-06-25 20:32 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +      if (response) {
response может быть не определен?

2022-06-25 20:32 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +      Logger.error(`Order '${paidOrder.id}' not registered in Bnovo`)
Сейчас сюда будут валиться ошибки из ТГ. Надо либо сделать 2 разных try catch, либо здесь их различать.

Еще неплохой паттерн - не использовать try catch, а вместо этого ставить .catch тем операциям от которых ничто дальше в коде не зависит.

2022-06-25 20:32 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +      const error = err as Error
Посмотри мой комментарий ниже по похожей строчке.

2022-06-25 20:32 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +import Logger from '@ioc:Adonis/Core/Logger'
А линт это не подсвечивает?

2022-06-25 20:32 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +  private async sendRequest<T extends Record<string, void>>(
Это очень странный тип) Что пытаешься вернуть-то?

2022-06-25 20:36 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +      if (response) {
АА! понял )))

2022-06-25 21:03 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +import Logger from '@ioc:Adonis/Core/Logger'
подсвечивал, пока я его не убил, а перенастроить всё руки не доходят

2022-06-26 21:32 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +      Logger.error(`Order '${paidOrder.id}' not registered in Bnovo`)
try-catch есть ещё и в ТГ

2022-06-26 21:32 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +      const error = err as Error
исправил

2022-06-26 21:32 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +      if (response) {
исправил

2022-06-26 21:36 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +  private async sendRequest<T extends Record<string, void>>(
намудрил((( но когда делал выглядело приемлемо

2022-06-27 07:33 UTC, AntePost requested changes

2022-06-27 07:33 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +      if (response.bookings) {
А если нет?

2022-06-27 07:33 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +      return creatingErrMsg('Failed bnovo response.', 'Unknown error')
Все равно лучше вернуть саму ошибку. И залогировать.

2022-06-27 07:33 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +        Logger.error(`Order '${paidOrder.id}' (${paidOrder.apartmentAddress}) not registered in Bnovo`)
Тут тоже можно ошибку залогировать.

2022-06-27 07:33 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +  ): Promise<{ ok: boolean } & Record<string, void>> {
Уже лучше, но все равно странный тип) После &

2022-06-27 07:33 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +        const error = err
Зачем?

2022-06-30 20:06 UTC, RimidalU commented on packages/backend/app/Services/OrderServices.ts
> +        const error = err
Исправил

2022-07-01 17:21 UTC, AntePost requested changes

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +  telegramBot
```suggestion
  private bnovo: Bnovo
  private telegramBot: Telegram
```
Либо можно указать модификатор видимости в параметрах конструктора и тогда вообще эти свойства не нужны.

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +import TelegramBot from 'App/Services/Telegram'
Лучше, чтобы default export и файл одинаково назывались.

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +  public async notifyPayment (
```suggestion
  public async sendBookingNotification (
```

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +        Logger.error(`Order '${paidOrder.id}' (${paidOrder.apartmentAddress}) not registered in Bnovo, Bnovo response: '${util.inspect(response)}'`)
```suggestion
        Logger.error(`Order '${paidOrder.id}': failed to book (${paidOrder.apartmentAddress}) in Bnovo, Bnovo response: '${util.inspect(response)}'`)
```

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/OrderServices.ts
> +        return creatingErrMsg('Failed bnovo response.', `Bnovo response: ${util.inspect(response)}`)
```suggestion
        return creatingErrMsg('error.', `failed to book (${paidOrder.apartmentAddress}) in Bnovo`)
```
Ниже по аналогии.

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +  private readonly config: ITelegram
```suggestion
  private readonly config: ITelegramConfig
```
Или прямо telegramConfiguration как тип использовать.

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +    _data?: IMsgToTelegram
Это зачем?

2022-07-01 17:21 UTC, AntePost commented on packages/backend/app/Services/Telegram.ts
> +      return creatingOkMsg(telegramResponse)
```suggestion
      return creatingOkMsg(telegramResponse)
```
Реальный ответ слать на фронт не стоит. Просто текстом, что успешно забронировал. И вообще лучше, чтобы успешный ответ уходил, когда получилось забронировать. А неуспешная отправка в ТГ только в логах отражалась.

2022-07-02 14:25 UTC, RimidalU commented on packages/backend/app/Services/Telegram.ts
> +    _data?: IMsgToTelegram
первоначально хотел сделать добавление произвольных данных, но, наверное уже и не нужно. Удалю

2022-07-02 20:30 UTC, AntePost commented on packages/backend/app/Services/TelegramBot.ts
> +// import { IMsgToTelegram } from '../../common/interfaces/IMsgToTelegram'
```suggestion
```

2022-07-02 20:30 UTC, AntePost commented on packages/backend/config/telegram.ts
> +  telegram_bot_token: Env.get('TELEGRAM_BOT_TOKEN') as string,
packages/backend/env.ts тут можно типы прописать.

2022-07-03 17:38 UTC, AntePost approved these changes

2022-07-03 17:47 UTC, merged